language: go
go:
  - 1.11.x

sudo: required

install: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libpcap-dev libnetfilter-queue-dev iptables-dev

script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
