name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  checks:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libnetfilter-queue-dev libpcap-dev iptables lsof
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"
      - run: make test
